### ISSUE TITLE
Increase height of the navigation bar.

### ISSUE THREAD

**Issue by Shivamroy4** [BlackrockDigital/startbootstrap-small-business#1]
I want to increase the height of the navigation bar , that is , the black coloured area at the top of the page. It would be a great help , if you could tell me how to do so . It want to increase the height as I have removed the buttons and I want just the Title of my page to be displayed there in quite big fonts. The title is moving out of the black bar , so I want the black bar to be a bit bigger to display the title neatly.
Thank You in advance .

**Comment by davidtmiller** [comment]
The best way to do this is to add padding to the `.nav > li > a' element. Top and bottom padding on those links will increase the height of the navigation in a good way. Another option is to add top and bottom padding to the `.navbar` class, or creating a custom class and adding that to the navigation that has top and bottom padding.
